name: Test

on:
  push:
    branches:
      - main
      - "releases/**"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2.3.0
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
